- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/khang859/config.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    force: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
- name: Copy config files to .config folder
  shell: rm -rf "$HOME/.config/nvim" && mkdir "$HOME/.config/nvim" && cp -R "$HOME/.dotfiles/nvim" "$HOME/.config"
  tags:
    - install
    - dotfiles

- name: Copy tmux config to .config folder
  shell: rm -rf "$HOME/.config/.tmux.conf" && cp "$HOME/.dotfiles/.tmux.conf" "$HOME/.config/.tmux.conf"
  tags:
    - install
    - dotfiles
