- name: Install packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Download ripgrep
  shell: 'curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb'
- name: Instal ripgrep
  become: yes
  become_method: sudo
  shell: 'sudo dpkg -i ripgrep_13.0.0_amd64.deb'
- name: Clean up ripgrep install file
  file:
    path: './ripgrep_13.0.0_amd64.deb'
    state: absent
