# Install formula foo with 'brew' in default path
- name: Get Neovim via Brew
  community.general.homebrew:
    name: neovim
    state: present
  tags:
    - install
    - neovim
- name: Get ripgrep
  community.general.homebrew:
    name: ripgrep
    state: present
  tags:
    - install
    - neovim
- name: Install packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
